jobs:
  # configs
  - job: build_linux
    displayName: 'Build Rust project on Linux'
    pool:
      vmImage: 'ubuntu-latest'

    # actions
    steps:

      # install rust
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install rust

      # check packages
      - script: cargo check
        workingDirectory: ./main
        displayName: Check dependencies

      # run tests
      - script: cargo test
        workingDirectory: ./main
        displayName: Run tests