jobs:
  # configs
  - job: build_linux
    displayName: 'Build Rust project on Linux (in)'
    pool:
      vmImage: 'ubuntu-latest'

    # actions
    steps:

      # install rust
      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        env:
          RUSTUP_TOOLCHAIN: ${{parameters.rust}}
          displayName: "Install rust (*nix)"
      env:
        RUSTUP_TOOLCHAIN: ${{parameters.rust}}
        displayName: "Install rust (linux)"

      # check packages
      - script: cargo check
        workingDirectory: ${{ parameters.dir }}
        displayName: cargo check