jobs:
  # config
  - job: build_windows
    displayName: 'Build Rust project on Windows (in)'
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self  # Check out the repository

      # install rust
      - script: |
          choco install rust --version $(rustVersion) -y
          refreshenv  # Refresh environment variables
        displayName: 'Install Rust $(rustVersion)'

      # Build steps specific to Windows
      - script: cargo build --release
        displayName: 'Cargo build (release)'

      # Add more steps as needed for testing, packaging, etc.