jobs:
  # configs
  - job: build_windows
    displayName: 'Build Rust project on Windows (in)'
    pool:
      vmImage: 'windows-latest'

    # actions
    steps:

      # install rust
      - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --profile minimal --default-toolchain %RUSTUP_TOOLCHAIN% --default-host x86_64-pc-windows-msvc
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
      displayName: Install rust

      # check packages
      - script: cargo check
        workingDirectory: ${{ parameters.dir }}
        displayName: Check dependencies