jobs:
  # configs
  - job: build_windows
    displayName: 'Build Rust project on Windows (in)'
    pool:
      vmImage: 'windows-latest'

    # actions
    steps:

      # install rust
      - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      env:
        RUSTUP_TOOLCHAIN: ${{parameters.rust}}
        displayName: "Install rust (windows)"

      # check build working
      - script: cargo check
        workingDirectory: ${{ parameters.dir }}
        displayName: cargo check